steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: yarn
  args: ["run", "create-env"]
  env:
    - 'VALORANT_API_KEY=${_VALORANT_API_KEY}'
- name: node
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 300 && gcloud app deploy']
timeout: '300s'